spring:
  application:
    name: login
  datasource:
    url: jdbc:postgresql://localhost:5432/hulkstore
    username: postgres
    password: Plac3t0g0
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      idle-timeout: 10000
      poolName: poolLogin
  jpa:
    generate-ddl: true
    show-sql: true
#    hibernate:
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#      ddl-auto: create-drop

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: gateway,health,info


#Port - If 0 get random port
server:
  port: 8082
